<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3xKZlhX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3xKZlhX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3xKZlhX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3xKZlhX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3xKZlhX\App_KernelDevDebugContainer([
    'container.build_hash' => '3xKZlhX',
    'container.build_id' => '05af5527',
    'container.build_time' => 1580200808,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3xKZlhX');
